verify_signatures: true

CommitMsg:
  HardTabs:
    enabled: true

PreCommit:
  HardTabs:
    enabled: true
    exclude:
      - 'Makefile'

  JsonSyntax:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
