# Ensure we use the version of Overcommit (and other gems) specified in the Gemfile
gemfile: .overcommit_gems.rb

# Don't need this for a private repo
verify_signatures: false

CommitMsg:
  GerritChangeId:
    enabled: true

  HardTabs:
    enabled: true

PreCommit:
  AuthorEmail:
    enabled: true
    description: 'Checking author email for Brigade domain'
***REMOVED***

  HardTabs:
    enabled: true
    exclude:
      - 'Makefile'

  JsonSyntax:
    enabled: true

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
