# Ensure we use the version of Overcommit (and other gems) specified in the Gemfile
gemfile: Gemfile

CommitMsg:
  GerritChangeId:
    enabled: true

  HardTabs:
    enabled: true

PreCommit:
  ALL:
    exclude:
      - 'vendor/**/*'

  AuthorEmail:
    enabled: true
    description: 'Checking author email for Brigade domain'
***REMOVED***

  HardTabs:
    enabled: true
    description: 'Checking for hard tabs'
    exclude:
      - 'Makefile'

  JsonSyntax:
    enabled: true

  MergeConflicts:
    enabled: true

  TrailingWhitespace:
    enabled: true

# Don't need this for a private repo
verify_signatures: false
