version: '2'

services:
  gunicorn:
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_UID:
      APP_GID:
    network_mode: host
    volumes:
      - '.:/workspace'
    working_dir: '/workspace'
    command: ['env/bin/gunicorn', 'web:app', '-b', '0.0.0.0:3000', '--log-file=-']

  elasticsearch:
    image: 'brigade/elasticsearch:1.7-latest'
    environment:
      APP_UID:
      APP_GID:
    network_mode: host
    tmpfs:
      - '/usr/share/elasticsearch/data:size=1G'
    command: ['elasticsearch', '--action.write_consistency=one']
