version: '2'

services:
  verifier_base:
    build:
      context: .
      dockerfile: dock/bootstrap_dockerfile
    environment:
      APP_UID:
      APP_GID:
    ports:
      - '11012:3000'
    volumes:
      - '.:/src'
    working_dir: '/src'
    command: ['env/bin/gunicorn', 'web:app', '-b', '0.0.0.0:3000', '--log-file=-']

  verifier:
    extends:
      service: verifier_base
    depends_on:
      - elasticsearch

  verifier_test:
    extends:
      service: verifier_base
    depends_on:
      - elasticsearch_test

  elasticsearch:
    extends:
      file: $BASE_COMPOSE
      service: elasticsearch_dev_base
    command: ['elasticsearch', '--action.write_consistency=one']

  elasticsearch_test:
    extends:
      file: $BASE_COMPOSE
      service: elasticsearch_test_base
    command: ['elasticsearch', '--action.write_consistency=one']

volumes:
  elasticsearch:
