version: '2.1'

services:
  verifier_base:
    build:
      context: .
      dockerfile: dock/bootstrap_Dockerfile
    healthcheck:
      test: curl localhost:3000
      interval: 1s
      timeout: 10s
      retries: 120
    environment:
      APP_UID:
      APP_GID:
      ARCANUS_PASSWORD: ${ARCANUS_PASSWORD_VERIFIER}
      ELASTICSEARCH_HOSTS: http://docker-host:9200/
      FLASK_ENV: 'development'
    ports:
      - '11012:3000'
    volumes:
      - '.:/src'
    working_dir: '/src'
    command: bash -c 'dock/initialize && dock/datastore_setup && dock/run'

  verifier:
    extends:
      service: verifier_base
    depends_on:
      elasticsearch:
        condition: service_healthy

  verifier_test:
    extends:
      service: verifier_base
    depends_on:
      elasticsearch_test:
        condition: service_healthy

  elasticsearch:
    extends:
      file: $BASE_COMPOSE
      service: elasticsearch_dev_base
    command: ['elasticsearch', '--action.write_consistency=one']

  elasticsearch_test:
    extends:
      file: $BASE_COMPOSE
      service: elasticsearch_test_base
    command: ['elasticsearch', '--action.write_consistency=one']

volumes:
  elasticsearch:
