version: '2'

services:
  gunicorn:
    depends_on:
      - elasticsearch
    image: brigade/centos:7.2.1511-latest
    environment:
      APP_UID:
      APP_GID:
    network_mode: host
    volumes:
      - '.:/workspace'
    working_dir: '/workspace'
    command: ['env/bin/gunicorn', 'web:app', '-b', '0.0.0.0:3000', '--log-file=-']

  elasticsearch:
    extends:
      file: $BASE_COMPOSE
      service: elasticsearch_base
    tmpfs:
      - '/usr/share/elasticsearch/data:size=1G'
    command: ['elasticsearch', '--action.write_consistency=one']
